### PR TITLE
Rails 5.1 support

### PR DESCRIPTION
**Pull request by zharikovpro**

### CODE REVIEW

**Comment by zharikovpro** [comment]
Will much appreciate patch release for this and schema_validations. Can barely live without Rails 5.1 and those lovely gems. They are real gems!

**Comment by onomated** [comment]
@ronen Bringing back to your attention.  We would really love to have this patch released.  Rails 5.1 has been out for a while now

**Comment by ronen** [comment]
@onomated thanks for the ping, and @zharikovpro apologies for the silence.

Unfortunately it's not as simple as just broadening the dependencies.  These gems all depend on schema_plus_core, and as per SchemaPlus/schema_plus_core#19 that needs to be updated to AR 5.1 -- and very unfortunately I myself don't currently have the time to do it.  I'm not using AR 5.1 for any of my jobs and don't have enough free time to do it on my own.   So really hoping somebody out there reading this will jump in...

(BTW the reason that the tests pass with this PR is that the tests aren't run on AR 5.1; the file `schema_dev.yaml` lists the versions of AR to test; if you update that to include 5.1 you'll see that it can't resolve the dependencies...)

**Comment by ronen** [comment]
Thanks to @iagopiimenta, schema_plus_core has been updated. Then it was a quick matter for me to update this gem. Version 0.2.0 is released now.

**Pull request closed without merging**
